# https://golangci-lint.run/usage/configuration/

run:
  skip-dirs:
    - testdata

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - godot
    - godox
    - prealloc
    - exportloopref
    - promlinter
    - tagliatelle
    - asciicheck
    - durationcheck
    - exhaustive
    - errorlint
    - gomoddirectives
    - gomodguard
    - importas
    - makezero
    - nestif
    - nilerr
    - noctx
    - predeclared
    - forcetypeassert
    - goheader
    - bidichk
    - tenv
    - errname
