before:
  hooks:
    - go clean
    - go mod download

builds:
  - id: ddns
    main: ./cmd/ddns/main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    ldflags:
      - -s -w -X main.Version={{.Tag}}
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - 386

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-{{ .Version }}"
    format: binary
    replacements:
      amd64: x86_64

changelog:
  skip: true

dockers:
  - image_templates:
      - "ghcr.io/milgradesec/{{ .ProjectName }}:amd64"
    dockerfile: build.Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform linux/amd64"
      - "--tag ghcr.io/milgradesec/{{ .ProjectName }}:amd64"

  - image_templates:
      - "ghcr.io/milgradesec/{{ .ProjectName }}:arm64"
    dockerfile: build.Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform linux/arm64"
      - "--tag ghcr.io/milgradesec/{{ .ProjectName }}:arm64"

docker_manifests:
  - name_template: ghcr.io/milgradesec/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - ghcr.io/milgradesec/{{ .ProjectName }}:amd64
      - ghcr.io/milgradesec/{{ .ProjectName }}:arm64
