before:
  hooks:
    - go clean
    - go mod download

builds:
  - id: ddns
    main: ./cmd/ddns/main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Tag}}
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - 386

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-{{ .Version }}"
    format: binary
    replacements:
      amd64: x86_64

changelog:
  skip: true
