before:
  hooks:
    - go mod tidy

builds:
  - id: ddns
    env:
      - CGO_ENABLED=0
    main: ./cmd/ddns/main.go
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Tag}}
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - 386

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-v{{ .Version }}"
    format: binary
    replacements:
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

changelog:
  skip: true
