version: "3.7"

configs:
  ddns_config.json:
    external: true

services:
  ddns:
    image: milgradesec/ddns:latest
    configs:
      - source: ddns_config.json
        target: /config.json
    secrets:
      - ddns_api_token
    environment:
      - CLOUDFLARE_API_TOKEN_FILE=ddns_api_token
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

secrets:
  ddns_api_token:
    external: true
