version: "3.8"

configs:
  config.json:
    file: config.json

services:
  ddns:
    image: milgradesec/ddns:latest
    configs:
      - source: config.json
        target: /config.json
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
