name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22

      - name: Build
        run: make build

      - name: Run tests with coverage
        run: make cover

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
