name: Docker Build and Push

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: echo TAG=${GITHUB_REF#refs/*/} >> $GITHUB_ENV

      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push
        run: docker buildx build -f build.Dockerfile --platform linux/arm/v7 . --tag milgradesec/ddns:$TAG --tag milgradesec/ddns:latest --push
