name: Docker Build and Push

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: echo TAG=${GITHUB_REF#refs/*/} >> $GITHUB_ENV

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push
        run: |
          docker buildx build -f build.Dockerfile --platform linux/amd64 . --tag ghcr.io/milgradesec/ddns:amd64 --push
          docker buildx build -f build.Dockerfile --platform linux/arm64 . --tag ghcr.io/milgradesec/ddns:arm64 --push
          docker manifest create ghcr.io/milgradesec/ddns:$TAG ghcr.io/milgradesec/ddns:arm64 ghcr.io/milgradesec/ddns:amd64
          docker manifest create ghcr.io/milgradesec/ddns:latest ghcr.io/milgradesec/ddns:arm64 ghcr.io/milgradesec/ddns:amd64
          docker manifest push --purge ghcr.io/milgradesec/ddns:$TAG
          docker manifest push --purge ghcr.io/milgradesec/ddns:latest
