on: push

name: Create Release

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go 1.14
        id: go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
